Nodes:
- Host: 172.17.0.2:8000
  SshPort: 22
  InnerNetworkHost: 172.17.0.2:8000
PathToSshKey: /root/.ssh/id_rsa
SshUsername: root
CopyAliens: true
RestartAfterCopy: true
RemoveCopiedFiles: true
