name: build-packages

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
    branches:
      - 73-fix-version-checking-job

jobs:

  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set env
        run: |
          echo "VERSION=$(cat versions.props | grep InformationalVersion | sed 's/<.*>\(.*\)<.*>/\1/' | sed s/'\s'//g)" >> $GITHUB_ENV
          echo "TAG_NAME=$(echo 'refs/tags/v2.0.0-alpha.19' | cut -d / -f 3) | sed -e 's/^v//'" >> $GITHUB_ENV
      - name: Version check
        if: ${{ env.VERSION }} != ${{ env.TAG_NAME }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Tag not match version in versions.props')

  build-binaries:
    runs-on: ubuntu-latest
    needs: check-version
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build release
        run: ./buildscripts/publish.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bob-tools-binaries
          path: publish

  build-rpm:
    runs-on: ubuntu-latest
    needs: [build-binaries, check-version]
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: bob-tools-binaries
      - name: Set env
        run: echo "VERSION=$(cat versions.props | grep InformationalVersion | sed 's/<.*>\(.*\)<.*>/\1/' | sed s/'\s'//g | sed -e 's/-/./g')" >> $GITHUB_ENV
      - name: build rpm
        run: |
          sed -i "s/current_version/${{ env.VERSION }}/" linux-packages/bob-tools.spec
          sed -i "s/release_number/${{ github.run_id }}/" linux-packages/bob-tools.spec
          mkdir -p ./rpmbuild/{SOURCES,BUILD,RPMS,SPECS,SRPMS}
          cur_dir_name=${PWD##*/}
          tar czf ./rpmbuild/SOURCES/bob-tools-${{ env.VERSION }}.tar.gz ../${cur_dir_name}/{ClusterModifier,DisksMonitoring,BobAliensRecovery,OldPartitionsRemover,RecordsCalculator,linux-packages/DisksMonitoring.service,publish/BobTools.sh} --transform s/${cur_dir_name}/bob-tools-${{ env.VERSION }}/
          rpmbuild -ba --define "_topdir ${PWD}/rpmbuild" linux-packages/bob-tools.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bob-tools-rpm
          path: rpmbuild/RPMS/x86_64/bob-tools-${{ env.VERSION }}-${{ github.run_id }}.x86_64.rpm

  upload-rpm:
    runs-on: ubuntu-latest
    needs: [build-rpm, check-version]
    environment: prod
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: bob-tools-rpm
      - name: Set env
        run: echo "VERSION=$(cat versions.props | grep InformationalVersion | sed 's/<.*>\(.*\)<.*>/\1/' | sed s/'\s'//g | sed -e 's/-/./g')" >> $GITHUB_ENV
      - name: Upload rpm to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bob-tools-${{ env.VERSION }}-${{ github.run_id }}.x86_64.rpm
          asset_name: bob-tools-${{ env.VERSION }}.x86_64.rpm
          tag: ${{ github.ref }}
          overwrite: true

  build-deb:
    runs-on: ubuntu-latest
    needs: [build-binaries, check-version]
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: bob-tools-binaries
      - name: Set env
        run: echo "VERSION=$(cat versions.props | grep InformationalVersion | sed 's/<.*>\(.*\)<.*>/\1/' | sed s/'\s'//g | sed -e 's/-/./g')" >> $GITHUB_ENV
      - name: build deb
        run: |
          mkdir -p bob-tools_${{ env.VERSION }}_amd64/{DEBIAN,usr/bin,etc/DisksMonitoring,etc/systemd/system,lib/systemd/system}
          cp linux-packages/control bob-tools_${{ env.VERSION }}_amd64/DEBIAN/
          cp {ClusterModifier,DisksMonitoring,BobAliensRecovery,OldPartitionsRemover,RecordsCalculator} bob-tools_${{ env.VERSION }}_amd64/usr/bin/
          cp publish/BobTools.sh bob-tools_${{ env.VERSION }}_amd64/usr/bin/bobtools
          chmod +x bob-tools_${{ env.VERSION }}_amd64/usr/bin/{ClusterModifier,DisksMonitoring,BobAliensRecovery,OldPartitionsRemover,RecordsCalculator,bobtools}
          cp linux-packages/DisksMonitoring.service bob-tools_${{ env.VERSION }}_amd64/etc/systemd/system/
          cp linux-packages/DisksMonitoring.service bob-tools_${{ env.VERSION }}_amd64/lib/systemd/system/
          sed -i "s/current_version/${{ env.VERSION }}/" bob-tools_${{ env.VERSION }}_amd64/DEBIAN/control
          dpkg-deb --build ./bob-tools_${{ env.VERSION }}_amd64
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bob-tools-deb
          path: bob-tools_${{ env.VERSION }}_amd64.deb

  upload-deb:
    runs-on: ubuntu-latest
    needs: [build-deb, check-version]
    environment: prod
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: bob-tools-deb
      - name: Set env
        run: echo "VERSION=$(cat versions.props | grep InformationalVersion | sed 's/<.*>\(.*\)<.*>/\1/' | sed s/'\s'//g | sed -e 's/-/./g')" >> $GITHUB_ENV
      - name: Upload deb to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bob-tools_${{ env.VERSION }}_amd64.deb
          asset_name: bob-tools_${{ env.VERSION }}_amd64.deb
          tag: ${{ github.ref }}
          overwrite: true

  zip-file:
    runs-on: ubuntu-latest
    needs: [build-binaries, check-version]
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: bob-tools-binaries
      - name: Set env
      - name: Set env
        run: echo "VERSION=$(cat versions.props | grep InformationalVersion | sed 's/<.*>\(.*\)<.*>/\1/' | sed s/'\s'//g | sed -e 's/-/./g')" >> $GITHUB_ENV
      - name: Create file structure 
        run: |
          mkdir -p bob-tools_${{ env.VERSION }}/{usr/bin,etc/DisksMonitoring,etc/systemd/system,lib/systemd/system}
          cp {ClusterModifier,DisksMonitoring,BobAliensRecovery,OldPartitionsRemover,RecordsCalculator} bob-tools_${{ env.VERSION }}/usr/bin/
          cp publish/BobTools.sh bob-tools_${{ env.VERSION }}/usr/bin/bobtools
          chmod +x bob-tools_${{ env.VERSION }}/usr/bin/{ClusterModifier,DisksMonitoring,BobAliensRecovery,OldPartitionsRemover,RecordsCalculator,bobtools}
          cp linux-packages/DisksMonitoring.service bob-tools_${{ env.VERSION }}/etc/systemd/system/
          cp linux-packages/DisksMonitoring.service bob-tools_${{ env.VERSION }}/lib/systemd/system/
          zip -r bob-tools_${{ env.VERSION }}.zip bob-tools_${{ env.VERSION }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bob-tools-zip
          path: bob-tools_${{ env.VERSION }}.zip

  upload-zip:
    runs-on: ubuntu-latest
    needs: [zip-file, check-version]
    environment: prod
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: bob-tools-zip
      - name: Set env
        run: echo "VERSION=$(cat versions.props | grep InformationalVersion | sed 's/<.*>\(.*\)<.*>/\1/' | sed s/'\s'//g | sed -e 's/-/./g')" >> $GITHUB_ENV
      - name: Upload zip file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bob-tools_${{ env.VERSION }}.zip
          asset_name: bob-tools_${{ env.VERSION }}.zip
          tag: ${{ github.ref }}
          overwrite: true
