name: build

on:
  pull_request:
      types: [ opened, synchronize, reopened, ready_for_review, labeled, unlabeled ]
  push:
    branches: [ master ]
    
jobs:

  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build release
        run: ./buildscripts/publish.sh